CREATE DATABASE SistemaInventarioDB
GO
USE SistemaInventarioDB
GO
CREATE TABLE Usuarios (
Id INT PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR (100) NOT NULL,
Correo NVARCHAR (150) UNIQUE NOT NULL,
PasswordHash NVARCHAR (500) NOT NULL,
Activo BIT NOT NULL
);
GO
CREATE TABLE Categoria (
Id INT PRIMARY KEY IDENTITY(1,1),
Nombre NVARCHAR (100) NOT NULL,
Descripcion NVARCHAR (150),
Activo BIT NOT NULL,
);
GO
CREATE TABLE Producto (
Id INT PRIMARY KEY IDENTITY(1,1),
Codigo NVARCHAR (30) NOT NULL,
Nombre NVARCHAR (120) NOT NULL,
Descripcion NVARCHAR (250),
Precio DECIMAL(10,2) NOT NULL,
Existencia INT NOT NULL,
CategoriaId INT,
Activo BIT NOT NULL,
CONSTRAINT fk_CategoriaId
FOREIGN KEY (CategoriaId) REFERENCES Categoria(Id)
);
GO
